services:
  - type: web
    name: smartfood
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py populate_food_items
    startCommand: gunicorn smartfood.wsgi:application
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com

databases:
  - name: smartfood-db
    databaseName: smartfood
    user: smartfood_user 